# -*- coding: utf-8 -*-
"""OSS0518.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cNr3PaQfH_RaNf145nhYpVV3WChSevjD
"""

from sklearn.model_selection import train_test_split
iris = datasets.load_iris()
X = iris.data
y = iris.target

#(80:20)으로 분할한다
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size =0.2,random_state=4)

print(X_train.shape)
print(X_test.shape)

from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=6)
knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)
from sklearn import metrics

scores = metrics.accuracy_score(y_test, y_pred)
print(scores)

classes = {0:'setosa', 1:'versicolor', 2:'virginica'}
# 전혀보지못한 새로운 데이터
x_new = [[3,4,5,2], [5,4,2,2]]
y_predict = knn.predict(x_new)
print(classes[y_predict[0]])
print(classes[y_predict[1]])

import matplotlib.pyplot as plt
from sklearn import datasets, metrics
from sklearn.model_selection import train_test_split
digits = datasets.load_digits()
plt.imshow(digits.images[0], cmap=plt.cm.gray_r, interpolation='nearest')

n_samples =len(digits.images)
data =digits.images.reshape(n_samples, -1)

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size =0.2)

from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=6)
knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)
scores = metrics.accuracy_score(y_test,y_pred)
print(scores)

plt.imshow(X_test[10].reshape(2,2),cmap=plt.cm.gray_r,interpolation='nearest')#원래는reshape(8,8)
y_pred = knn.predict([X_test[10]])
print(y_pred)