# -*- coding: utf-8 -*-
"""OSS_load_wine

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A9Bk_JA1spor27_Dj16UgRJcCX_LuWsa
"""

from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

wine = load_wine()
X = wine.data
y = wine.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(X_train.shape)
print(X_test.shape)
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)

scores = accuracy_score(y_test, y_pred)
print(f"기본 모델의 분류 정확도: {scores * 100:.2f}%")

classes = {0: 'class_0 (0번 품종)', 1: 'class_1 (1번 품종)', 2: 'class_2 (2번 품종)'}

x_new = [
    [13.2, 2.7, 2.4, 21.0, 105.0, 2.8, 3.2, 0.28, 1.3, 5.4, 1.0, 3.1, 1050.0],
    [12.0, 1.5, 2.0, 19.0,  85.0, 1.5, 1.0, 0.40, 1.0, 3.0, 1.2, 2.0,  450.0]
]
y_pred2 = knn.predict(x_new)

print("첫 번째 가상 와인의 예측 결과:", classes[y_pred2[0]])
print("두 번째 가상 와인의 예측 결과:", classes[y_pred2[1]])